### ISSUE TITLE
Can't sign tx to test if I am not part of the ms

### ISSUE THREAD

**Issue by poolpitako** [banteg/ape-safe#2]
CMO allowed me to test a tx and sign even when I was not an owner of a delegate of the ms.
With ape-safe I get:

```ApiError: Error posting transaction: b'{"nonFieldErrors":["Sender=0x0 is not an owner or delegate. Current owners=[\'0x0\', \'0x0\', \'0x6F2A8Ee9452ba7d336b3fba03caC27f7818AeAD6\']. Delegates=[]"]}'```

At the beginning I thought it was a gnosis upgrade, but I just run a tx with ape-safe installed and I could sign to test without issues.

I guess `ms.preview(tx)` is not doing the same thing as `estimate_safe_tx(safe_tx)`

**Comment by banteg** [comment]
This tool only requires signing on `post_transaction`.

`preview` and `estimate_gas` should work without a signature.
