### ISSUE TITLE
First example in the docs no longer works

### ISSUE THREAD

**Issue by jordaniza** [banteg/ape-safe#37]
Hi,

We've been using Ape Safe in the past with PieDAO but recent installs now fail to build. Even the quickstart example no longer works.

Investigating the issue and it seems that there are a few issues:

1. The Ethereum Client and the Contract address are not being correctly passed to the Gnosis Safe SDK
2. The gnosis-py library has been changed to safe-eth-py, it's not clear if the new dependencies are resolving correctly.
3. The Gnosis library packaged with ApeSafe makes calls (such as `get_contract`) that are either yet to be implemented or not correctly overriden

I'm happy to go into more details but, seeing that the quickstart no longer works and there have been no commits in over a year, I wanted to check if this library is even maintained, or if we need to find an alternative solution to building safe transactions?

**Comment by gosuto-inzasheru** [comment]
1. i proposed a fix for this in #46 
2. can you elaborate here? there is a good deepdive of the current state of dependencies [here](https://github.com/banteg/ape-safe/issues/43#issuecomment-1262912037)
3. this is addressed in #43, i have a local fix for it. i will see if i can pr it as well.

**Comment by banteg** [comment]
should be fixed in the latest release
